<a href="https://colab.research.google.com/github/a9garza/python_fundamentals/blob/main/Actividad_Ventas_Mensuales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Importar paquete NumPy
import numpy as np

In [19]:
#Parte 1
#Crea una matriz bidimensional (array) llamada ventas_mensuales con una dimensión de 12 filas (representando los meses del año) y 4 columnas (representando los productos vendidos).
#Los valores de la matriz representarán las ventas mensuales de cada producto. Puedes ingresar los valores manualmente.

#Se genera una matriz de 12 filas y 4 columnas, con valores enteros randomizados desde 2 a 5
ventas_mensuales=np.random.random_integers(2, 5, (12, 4))

#Imprimir Matriz
print(ventas_mensuales)

[[2 5 3 5]
 [3 5 5 3]
 [4 3 4 4]
 [3 4 2 3]
 [2 2 2 2]
 [3 4 3 2]
 [2 5 2 3]
 [2 2 3 5]
 [2 3 3 3]
 [4 5 3 4]
 [4 5 5 3]
 [3 4 3 5]]


<ipython-input-19-9c7078f6d8c7>:6: DeprecationWarning: This function is deprecated. Please call randint(2, 5 + 1) instead
  ventas_mensuales=np.random.random_integers(2, 5, (12, 4))


In [28]:
#Parte 2
#Calcula el total_de_ventas_producto sumando los valores de cada columna utilizando la función sum() de NumPy.

#Esta función suma todos los valores dentro de la matriz de ventas_mensuales
total_de_ventas_producto = np.sum(ventas_mensuales)
total_de_ventas_producto

161

In [31]:
#Esta función suma los valores de cada columna en la matriz de ventas_mensuales y genera un arreglo con los resultados
total_de_ventas_producto_columnas = np.sum(ventas_mensuales,axis=0)
print(total_de_ventas_producto_columnas)

[34 47 38 42]


In [33]:
#Esta función suma los valores de cada fila en la matriz de ventas_mensuales y genera un arreglo con los resultados
total_de_ventas_producto_filas = np.sum(ventas_mensuales,axis=1)
print(total_de_ventas_producto_filas)

[15 16 15 12  8 12 12 12 11 16 17 15]
