<a href="https://colab.research.google.com/github/a9garza/python_fundamentals/blob/main/Actividad%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#Importar paquete NumPy
import numpy as np

In [43]:
#Crea una matriz bidimensional (array) llamada matriz_3x3 con una dimensión de 3 filas y 3 columnas.
#Los valores de la matriz deben ir de 0 a 8. Puedes utilizar la función arange de NumPy para generar los valores de forma consecutiva.

#Generar una matriz de 1 dimensión con la serie de números de 0 a 8 utilizando arange
#Se utiliza del 0 al 9 ya que el conteo en python empieza desde 0
matriz_3x3 = np.arange(0,9)

#Utilizar función np.resize para darle la forma de 3x3 a la serie unidimensional anterior, creando una matriz de 2 dimensiones de 3 filas y 3 columnas
#Se iguala de nuevo al nombre de la variable para sobrescribir el arreglo original
matriz_3x3 = matriz_3x3 = np.resize(matriz_3x3,(3,3))

#Imprimir la matriz
print(matriz_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
